name: Test website and deploy on changes to main

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run
# in-progress and latest queued. However, do NOT cancel in-progress runs as we
# want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    container:
      image: ghcr.io/feldera/feldera-dev:0a775f772b2ebde13708744d3e6a219ca4a492d2

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Build Python SDK docs
        working-directory: ./feldera/python/docs
        run: |
          uv run sphinx-apidoc -o . ../feldera
          uv run sphinx-build -M html . _build
      - name: Copy the Python docs to static
        run: |
          cp -r feldera/python/docs/_build/html static/python
      - name: Build Docusaurus
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Upload docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  # Deployment job
  deploy_docs:
    # Only deploy on main
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4